"""empty message

Revision ID: 15050abab11c
Revises: 96f84511d7d
Create Date: 2015-08-04 22:45:33.857326

"""

# revision identifiers, used by Alembic.
revision = '15050abab11c'
down_revision = '96f84511d7d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
