"""empty message

Revision ID: 21d1d9769a4d
Revises: 3f2b5998de13
Create Date: 2015-08-09 03:08:43.518294

"""

# revision identifiers, used by Alembic.
revision = '21d1d9769a4d'
down_revision = '3f2b5998de13'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
