"""empty message

Revision ID: 2c6170a99fd6
Revises: 142e5e457be9
Create Date: 2015-08-07 22:51:47.696218

"""

# revision identifiers, used by Alembic.
revision = '2c6170a99fd6'
down_revision = '142e5e457be9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
