"""empty message

Revision ID: 3e4c18252c2e
Revises: bc9f272e0f0
Create Date: 2015-08-05 14:04:30.647139

"""

# revision identifiers, used by Alembic.
revision = '3e4c18252c2e'
down_revision = 'bc9f272e0f0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
