"""empty message

Revision ID: 3f2b5998de13
Revises: 186c2797787e
Create Date: 2015-08-08 05:42:19.675057

"""

# revision identifiers, used by Alembic.
revision = '3f2b5998de13'
down_revision = '186c2797787e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
