"""empty message

Revision ID: 96f84511d7d
Revises: 4c4c76ffdbca
Create Date: 2015-08-03 19:28:39.682618

"""

# revision identifiers, used by Alembic.
revision = '96f84511d7d'
down_revision = '4c4c76ffdbca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
